version: "3.8"

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'heatmap'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./heatmap:/var/lib/mysql
  web:
    restart: always
    volumes:
      - .:/srv/www
     # - sock:/sock для сокетов вместо портов
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    depends_on:
      - db
    #command: uwsgi --ini /etc/uwsgi.ini заменить команду на проде
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
  nginx:
    restart: always
    volumes:
        - .:/srv/www
       # - sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
        - web
    ports:
        - "8080:8080"